packages:
  - "src/apps/*"
  - "src/lib/utils"
  - "src/lib/cdm/typescript"
  - ".papi/descriptors"

catalog:
  polkadot-api: ^1.23.3
  "@polkadot-api/sdk-ink": ^0.6.2
  "@polkadot-api/smoldot": ^0.3.15
  "@polkadot-api/cli": ^0.18.1
  "@polkadot-labs/hdkd": ^0.0.26
  "@polkadot-labs/hdkd-helpers": ^0.0.27
  "@polkadot/util-crypto": ^14.0.1
  smoldot: ^2.0.40
  react: ^19.2.4
  react-dom: ^19.2.0
  react-router-dom: ^7.13.0
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  commander: ^12.0.0
  ink: ^6.8.0
  "@noble/hashes": ^2.0.1
  multiformats: ^13.4.2
  vite: ^7.3.1
  "@vitejs/plugin-react": ^5.1.1
  typescript: ^5.9.3
  turbo: ^2.3.0
  eslint: ^9.39.1
  "@eslint/js": ^9.39.1
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.24
  typescript-eslint: ^8.48.0
  globals: ^16.5.0
  dompurify: ^3.3.1
  marked: ^17.0.3
  "@types/dompurify": ^3.0.5
  "@types/node": ^24.10.1
  "@types/bun": latest
