/**
 * Reads all template directories under templates/ and generates
 * a TypeScript module that embeds their file contents.
 *
 * Run: bun run scripts/embed-templates.ts
 * Output: src/generated/templates.ts
 */

import { readdirSync, readFileSync, writeFileSync, mkdirSync, statSync } from "fs";
import { join, relative } from "path";

const PACKAGE_ROOT = join(import.meta.dir, "..");
const SRC_ROOT = join(import.meta.dir, "../../..");
const TEMPLATES_DIR = join(SRC_ROOT, "templates");
const OUT_FILE = join(PACKAGE_ROOT, "src/generated/templates.ts");

const IGNORE = new Set(["target", "node_modules", ".DS_Store", "Cargo.lock"]);

function collectFiles(dir: string, base: string): Record<string, string> {
    const files: Record<string, string> = {};
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
        if (IGNORE.has(entry.name)) continue;
        const fullPath = join(dir, entry.name);
        if (entry.isDirectory()) {
            Object.assign(files, collectFiles(fullPath, base));
        } else {
            const relPath = relative(base, fullPath);
            files[relPath] = readFileSync(fullPath, "utf-8");
        }
    }
    return files;
}

function escapeTemplateString(s: string): string {
    return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

// Discover all template directories
const templateDirs = readdirSync(TEMPLATES_DIR, { withFileTypes: true }).filter((d) =>
    d.isDirectory(),
);

let output = "// Auto-generated by scripts/embed-templates.ts — do not edit\n\n";

const names: string[] = [];

for (const dir of templateDirs) {
    const templatePath = join(TEMPLATES_DIR, dir.name);
    const files = collectFiles(templatePath, templatePath);
    const varName = dir.name.replace(/-([a-z])/g, (_, c) => c.toUpperCase()) + "Template";
    names.push(dir.name);

    output += `export const ${varName}: Record<string, string> = {\n`;
    for (const [path, content] of Object.entries(files)) {
        output += `  ${JSON.stringify(path)}: \`${escapeTemplateString(content)}\`,\n`;
    }
    output += "};\n\n";
}

output += `export const TEMPLATES: Record<string, { files: Record<string, string> }> = {\n`;
for (const name of names) {
    const varName = name.replace(/-([a-z])/g, (_, c) => c.toUpperCase()) + "Template";
    output += `  ${JSON.stringify(name)}: { files: ${varName} },\n`;
}
output += "};\n";

mkdirSync(join(PACKAGE_ROOT, "src/generated"), { recursive: true });
writeFileSync(OUT_FILE, output);
console.log(`Embedded ${names.length} template(s): ${names.join(", ")}`);
console.log(`Written to ${relative(PACKAGE_ROOT, OUT_FILE)}`);
